### ISSUE TITLE
Deaccent - Lower

### ISSUE THREAD

**Issue by soutsios** [nlpaueb/greek-bert#3]
Is there really a need to Pre-process text (Deaccent - Lower) as described in  https://github.com/nlpaueb/greek-bert#pre-process-text-deaccent---lower since its already something that bert tokenizer does (https://github.com/google-research/bert#tokenization) ?

**Comment by iliaschalkidis** [comment]
No it's not. The tokenizer does it automatically. Sorry for the belated response...
